// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_nBIgbf7gCnMxUlT2D6oOimqk8vj6HjU',
    appId: '1:956710344739:web:0a11c73771314d98fa7996',
    messagingSenderId: '956710344739',
    projectId: 'book-store-366e8',
    authDomain: 'book-store-366e8.firebaseapp.com',
    storageBucket: 'book-store-366e8.appspot.com',
    measurementId: 'G-YCK35N45NB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7lJdRYTbLF8iKdDAEh1xUxoUwdfJTBRM',
    appId: '1:956710344739:android:8764101f7d45d2e6fa7996',
    messagingSenderId: '956710344739',
    projectId: 'book-store-366e8',
    storageBucket: 'book-store-366e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATFuqC4tmRVYO6wWmIrA4P_aiswXjAm64',
    appId: '1:956710344739:ios:2a31e0a0775deeecfa7996',
    messagingSenderId: '956710344739',
    projectId: 'book-store-366e8',
    storageBucket: 'book-store-366e8.appspot.com',
    iosClientId: '956710344739-mrbcuqrheipuj8h745978juhahlilp2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATFuqC4tmRVYO6wWmIrA4P_aiswXjAm64',
    appId: '1:956710344739:ios:2a31e0a0775deeecfa7996',
    messagingSenderId: '956710344739',
    projectId: 'book-store-366e8',
    storageBucket: 'book-store-366e8.appspot.com',
    iosClientId: '956710344739-mrbcuqrheipuj8h745978juhahlilp2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookStore',
  );
}
